sudo: false
os:
  - linux
language: node_js
node_js:
  - '10'
  - '12'
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn lint
#  - yarn build Todo: enable when asc-assets don't have exported svg's
  - yarn build:example
branches:
  only:
    - master
deploy:
  - provider: pages
    local_dir: ./dist
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: prototype
      node: '12'
      os: linux
